In [1]:
import pandas as pd
import numpy as np
import string
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
input_files=[
    r"C:\Users\Sparsh Mahajan\OneDrive\Documents\lex programs\robert frost.txt",
    r"C:\Users\Sparsh Mahajan\OneDrive\Documents\lex programs\edger_allan_po.txt"
]

In [3]:
input_text=[]
label=[]
for  l , file  in enumerate(input_files):
    for line in open(file):
        line=line.rstrip().lower()
        if line:
            line = line.translate(str.maketrans('' , '',string.punctuation ))
            input_text.append(line)
            label.append(l)

In [4]:
#  0 robert frost
# 1 edger allan po
train_x , test_x , train_y , test_y = train_test_split(input_text , label)

In [5]:
print(train_x , train_y)

['and after all why should they johns been fair', 'in front of twenty others wriggling speed', 'hed say she does it more because she likes it', 'it was night in the lonesome october', 'besides the wear of iron wagon wheels', 'son looks surprised to see me end a lie', 'in a strange city all alone', 'a leak and emptied then and forty years', 'but only so an hour', 'a voice said look me in the stars', 'i was just coming to myself enough', 'there aint no names quite like the old ones though', 'whose shoes i primped to dance in', 'he and i only hinder one another', 'but if we must in sunshine so she went', 'i could not say', 'son we think they had a grave down in the cellar', 'it lifts existence on a plane of snow', 'though not yet light', 'he knows hes kinder than the run of men', 'it doesnt seem as if id had the courage', 'how often we forget all time when lone', 'toffile agreed to that and sure enough', 'by good angels tenanted', 'a brush had left a crooked stroke', 'and from barn smells

In [6]:
idx=1
word2idx={'<unk>':0}
for text in train_x:
    tokens=text.split()
    for token in tokens:
        if token not in word2idx:
            word2idx[token]=idx
            idx+=1

In [7]:
len(word2idx)

2534

In [8]:
train_text_int =[]
test_text_int=[]

for text in train_x:
    tokens=text.split()
    line_as_int=[word2idx[token] for token in tokens]
    train_text_int.append(line_as_int)
    
for text in test_x:
    tokens=text.split()
    line_as_int=[word2idx.get(token , 0) for token in tokens]
    test_text_int.append(line_as_int)

In [9]:
V=len(word2idx)+1

In [62]:
test_text_int

[[203, 79, 0, 1502, 38, 1044, 19, 2301, 0],
 [184, 27, 0, 12, 55, 2062, 12, 0],
 [113, 114, 84, 115, 3, 116, 117, 118],
 [27, 156, 1191, 1301, 27, 0, 179],
 [12, 249, 25, 1643, 1754, 297, 0],
 [168, 0, 3, 1088, 184, 170, 0, 1105],
 [545, 490, 491, 27, 492, 146, 493, 373],
 [170, 354, 170, 354, 61, 2400, 1, 0],
 [1185, 1186, 89, 0, 27, 0, 131, 211, 0],
 [529, 170, 1621, 246, 254, 66, 289, 101],
 [170, 1151, 170, 22, 105, 252],
 [616, 38, 565, 1029, 0, 61, 414, 0],
 [217, 289, 303, 0, 134, 351, 567, 0],
 [10, 27, 625, 626, 12, 426],
 [0, 6, 315, 456, 54, 0, 42, 0],
 [3, 2470, 12, 286, 38, 0, 249, 1567, 121, 1293],
 [81, 1, 81, 435, 545, 200, 66, 315, 566],
 [759, 249, 2038, 350, 885, 40, 163],
 [198, 415, 38, 1068],
 [200, 0, 0, 200, 81, 0, 1473],
 [719, 27, 0, 836, 249, 140, 0, 211],
 [1, 42, 0, 199, 10, 529, 27, 201],
 [27, 0, 79, 0, 184, 21],
 [752, 908, 315, 909, 1, 317],
 [184, 22, 12, 0, 105, 367, 0],
 [1, 0, 21, 184, 42, 0, 0],
 [0, 730, 121, 146, 27, 1177, 12, 1352],
 [10, 251, 1

In [10]:
A_0 = np.ones((V , V))
pi_0 = np.ones(V)

A_1 = np.ones((V , V))
pi_1 = np.ones(V)

In [98]:
def compute_count(text_as_int , A , pi , epsilon):
    
    for tokens in text_as_int:
        last_idx=None
        for idx in tokens:
            if last_idx is None :
                pi[idx]+=epsilon
            else:
                A[last_idx , idx]+=epsilon
            last_idx = idx
    A/=A.sum(axis=1 , keepdims=True)+V*epsilon
    pi/=pi.sum()+V*epsilon
    
compute_count([t for t,y in zip(train_text_int , train_y) if y==0] , A_0 , pi_0 , 1)
compute_count([t for t,y in zip(train_text_int , train_y) if y==1] , A_1, pi_1 , 1)
        

In [99]:
A_0

array([[9.45407734e-18, 9.45407734e-18, 9.45407734e-18, ...,
        9.45407734e-18, 9.45407734e-18, 9.45407734e-18],
       [6.32653846e-18, 6.32653846e-18, 6.72914118e-04, ...,
        6.32653846e-18, 6.32653846e-18, 6.32653846e-18],
       [9.36144189e-18, 9.36144189e-18, 9.36144189e-18, ...,
        9.36144189e-18, 9.36144189e-18, 9.36144189e-18],
       ...,
       [9.43545083e-18, 9.43545083e-18, 9.43545083e-18, ...,
        9.43545083e-18, 9.43545083e-18, 9.43545083e-18],
       [9.43545083e-18, 9.43545083e-18, 9.43545083e-18, ...,
        9.43545083e-18, 9.43545083e-18, 9.43545083e-18],
       [4.66962425e-18, 4.66962425e-18, 4.66962425e-18, ...,
        4.66962425e-18, 4.66962425e-18, 1.82416759e-11]])

In [70]:
pi_0

array([9.11124550e-15, 4.10199548e-02, 9.11124550e-15, ...,
       9.11124550e-15, 9.11124550e-15, 2.33554934e-11])

In [85]:
loga0 = np.log(A_0)
logpi0 = np.log(pi_0)
loga1 = np.log(A_1)
logpi1 = np.log(pi_1)

In [86]:
count0

1073

In [87]:
count0 = sum(y==0 for y in train_y)
count1 = sum(y==1 for y in train_y)

In [88]:
total= len(train_y)

In [89]:
p0=count0/total
p1=count1/total
logp0=np.log(p0)
logp1=np.log(p1)
p0 , p1

(0.6631644004944376, 0.3368355995055624)

In [90]:
class Classifier:
    def __init__(self , logA , logpi , logprior):
        self.logA = logA
        self.logpi= logpi
        self.logprior = logprior
        self.K = len(logprior)
        
        
        
    def _compute_log_likelihood(self , input_ , class_):
        logA=self.logA[class_]
        logpi = self.logpi[class_]
        lastidx=None
        logprob =0 
        for idx in input_:
            if lastidx is None:
                logprob+=logpi[idx]
            else:
                logprob+=logA[lastidx , idx]
            lastidx=idx
        return logprob
        
    
    
    
    def predict(self , inputs):
        pred=np.zeros(len(inputs))
        for i , input_ in enumerate(inputs):
            pos =[self._compute_log_likelihood(input_ , c)+self.logprior[c] for c in range(self.K)]
            pre=np.argmax(pos)
            pred[i]=pre
        return pred
            
        

In [100]:
clf= Classifier([loga0 , loga1] , [logpi0 , logpi1] , [logp0 , logp1])

In [101]:
ptrain = clf.predict(train_text_int)

In [102]:
print(f"train acc:{np.mean(ptrain==train_y)}")

train acc:1.0


In [103]:
ptest = clf.predict(test_text_int)
print(f"test acc:{np.mean(ptest==test_y)}")

test acc:0.8185185185185185


In [104]:
from sklearn.metrics import confusion_matrix , f1_score

In [105]:
cm=confusion_matrix(train_y , ptrain)

In [106]:
cm

array([[1073,    0],
       [   0,  545]], dtype=int64)

In [107]:
cm_test=confusion_matrix(test_y , ptest)
cm_test

array([[335,  28],
       [ 70, 107]], dtype=int64)

In [108]:
f1_score(train_y , ptrain)

1.0

In [109]:
f1_score(test_y , ptest)

0.6858974358974359