In [1]:
import numpy as np
import pandas as pd
import textwrap
import nltk
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer , PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to C:\Users\Sparsh
[nltk_data]     Mahajan\anaconda3\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Sparsh
[nltk_data]     Mahajan\anaconda3\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [20]:
import glob
import os

In [29]:
path = r"C:\Users\Sparsh Mahajan\Downloads\archive\bbc-fulltext (document classification)\bbc\*\*"

In [31]:
files[0].split("\\")[-2]

IndexError: list index out of range

In [32]:
files = glob.glob(path)

In [33]:
files

['C:\\Users\\Sparsh Mahajan\\Downloads\\archive\\bbc-fulltext (document classification)\\bbc\\business\\001.txt',
 'C:\\Users\\Sparsh Mahajan\\Downloads\\archive\\bbc-fulltext (document classification)\\bbc\\business\\002.txt',
 'C:\\Users\\Sparsh Mahajan\\Downloads\\archive\\bbc-fulltext (document classification)\\bbc\\business\\003.txt',
 'C:\\Users\\Sparsh Mahajan\\Downloads\\archive\\bbc-fulltext (document classification)\\bbc\\business\\004.txt',
 'C:\\Users\\Sparsh Mahajan\\Downloads\\archive\\bbc-fulltext (document classification)\\bbc\\business\\005.txt',
 'C:\\Users\\Sparsh Mahajan\\Downloads\\archive\\bbc-fulltext (document classification)\\bbc\\business\\006.txt',
 'C:\\Users\\Sparsh Mahajan\\Downloads\\archive\\bbc-fulltext (document classification)\\bbc\\business\\007.txt',
 'C:\\Users\\Sparsh Mahajan\\Downloads\\archive\\bbc-fulltext (document classification)\\bbc\\business\\008.txt',
 'C:\\Users\\Sparsh Mahajan\\Downloads\\archive\\bbc-fulltext (document classification)\

In [34]:
df = pd.DataFrame()

In [35]:
df['Type']=  [x.split("\\")[-2] for x in files]


In [36]:
text = []
for file in files:
    with open(file , 'r') as f:
        text.append(f.read())
    

In [37]:
df['text']= text

In [38]:
df

Type                                               text
0     business  Ad sales boost Time Warner profit\n\nQuarterly...
1     business  Dollar gains on Greenspan speech\n\nThe dollar...
2     business  Yukos unit buyer faces loan claim\n\nThe owner...
3     business  High fuel prices hit BA's profits\n\nBritish A...
4     business  Pernod takeover talk lifts Domecq\n\nShares in...
...        ...                                                ...
2220      tech  BT program to beat dialler scams\n\nBT is intr...
2221      tech  Spam e-mails tempt net shoppers\n\nComputer us...
2222      tech  Be careful how you code\n\nA new European dire...
2223      tech  US cyber security chief resigns\n\nThe man mak...
2224      tech  Losing yourself in online gaming\n\nOnline rol...

[2225 rows x 2 columns]

In [39]:
sample = df[df.Type=='tech']['text'].sample(random_state=42)

In [40]:
def wrap(x):
    return textwrap.fill(x , replace_whitespace=False , fix_sentence_endings=True)

In [41]:
print(wrap(sample.iloc[0]))

Peer-to-peer nets 'here to stay'

Peer-to-peer (P2P) networks are here
to stay, and are on the verge of being exploited by commercial media
firms, says a panel of industry experts.

Once several high-profile
legal cases against file-sharers are resolved this year, firms will be
very keen to try and make money from P2P technology.  The expert panel
probed the future of P2P at the Consumer Electronics Show in Las Vegas
earlier in January.  The first convictions for P2P piracy were handed
out in the US in January.  William Trowbridge and Michael Chicoine
pleaded guilty to charges that they infringed copyright by illegally
sharing music, movies and software.  Since the first successful file-
sharing network Napster was forced to close down, the entertainment
industry has been nervous and critical of P2P technology, blaming it
for falling sales and piracy.  But that is going to change very soon,
according to the panel.

The music and film industries have started
some big legal cases against

In [42]:
token = nltk.sent_tokenize(sample.iloc[0].split("\n" , 1)[1])

In [43]:
token

['\nPeer-to-peer (P2P) networks are here to stay, and are on the verge of being exploited by commercial media firms, says a panel of industry experts.',
 'Once several high-profile legal cases against file-sharers are resolved this year, firms will be very keen to try and make money from P2P technology.',
 'The expert panel probed the future of P2P at the Consumer Electronics Show in Las Vegas earlier in January.',
 'The first convictions for P2P piracy were handed out in the US in January.',
 'William Trowbridge and Michael Chicoine pleaded guilty to charges that they infringed copyright by illegally sharing music, movies and software.',
 'Since the first successful file-sharing network Napster was forced to close down, the entertainment industry has been nervous and critical of P2P technology, blaming it for falling sales and piracy.',
 'But that is going to change very soon, according to the panel.',
 'The music and film industries have started some big legal cases against owners of

In [44]:
featurizer = TfidfVectorizer(stop_words = stopwords.words('english') , norm='l1')

In [45]:
x = featurizer.fit_transform(token)
x

<40x306 sparse matrix of type '<class 'numpy.float64'>'
	with 465 stored elements in Compressed Sparse Row format>

In [46]:
def sentence_score(tfidf_row):
    z = tfidf_row[tfidf_row!=0]
    return z.mean()

In [47]:
scores = np.zeros(len(token))
for i in range(len(token)):
    score =sentence_score(x[i , : ])
    scores[i] = score

In [48]:
scores

array([0.07692308, 0.0625    , 0.08333333, 0.14285714, 0.07142857,
       0.05263158, 0.2       , 0.05882353, 0.05263158, 0.08333333,
       0.07692308, 0.06666667, 0.33333333, 0.2       , 0.09090909,
       0.0625    , 0.08333333, 0.125     , 0.16666667, 0.14285714,
       0.07142857, 0.2       , 0.11111111, 0.08333333, 0.2       ,
       0.06666667, 0.05882353, 0.05263158, 0.125     , 0.08333333,
       0.0625    , 0.06666667, 0.11111111, 0.0625    , 0.05555556,
       0.1       , 0.125     , 0.09090909, 0.08333333, 0.25      ])

In [49]:
score_idx = np.argsort(-scores)

In [50]:
score_idx 

array([12, 39, 24, 21, 13,  6, 18, 19,  3, 36, 17, 28, 32, 22, 35, 37, 14,
       23, 16, 38,  2,  9, 29, 10,  0,  4, 20, 25, 31, 11, 30, 33,  1, 15,
       26,  7, 34, 27,  5,  8], dtype=int64)

In [51]:
for i in score_idx[:5]:
    print(token[i])

"When they can't stop it, they try to control it.
"File-sharing is the tip of the iceberg."
But the technology is still demonised and misunderstood by many.
The BBC has already decided to embrace the technology.
Then they figure out how to make money and they always make a lot of money."


In [52]:
def summary(text):
    token = nltk.sent_tokenize(text)
    x = featurizer.fit_transform(token)
    scores = np.zeros(len(token))
    for i in range(len(token)):
        score = sentence_score(x[i , :])
        scores[i]=score
     
    for i in range (len(scores)):
        if scores[i]>=np.mean(scores):
            print(token[i])
    
        
    

In [53]:
df['text'][3]

'High fuel prices hit BA\'s profits\n\nBritish Airways has blamed high fuel prices for a 40% drop in profits.\n\nReporting its results for the three months to 31 December 2004, the airline made a pre-tax profit of £75m ($141m) compared with £125m a year earlier. Rod Eddington, BA\'s chief executive, said the results were "respectable" in a third quarter when fuel costs rose by £106m or 47.3%. BA\'s profits were still better than market expectation of £59m, and it expects a rise in full-year revenues.\n\nTo help offset the increased price of aviation fuel, BA last year introduced a fuel surcharge for passengers.\n\nIn October, it increased this from £6 to £10 one-way for all long-haul flights, while the short-haul surcharge was raised from £2.50 to £4 a leg. Yet aviation analyst Mike Powell of Dresdner Kleinwort Wasserstein says BA\'s estimated annual surcharge revenues - £160m - will still be way short of its additional fuel costs - a predicted extra £250m. Turnover for the q

In [54]:
summary(df['text'][3])

High fuel prices hit BA's profits

British Airways has blamed high fuel prices for a 40% drop in profits.
Turnover for the quarter was up 4.3% to £1.97bn, further benefiting from a rise in cargo revenue.
However, it said sales would be better than previously forecast.
BA had previously forecast a 2% to 3% rise in full-year revenue.
It also reported on Friday that passenger numbers rose 8.1% in January.
BA's shares closed up four pence at 274.5 pence.


Text Rank

In [59]:
from sklearn.metrics.pairwise import cosine_similarity

In [60]:
x = featurizer.fit_transform(token)
x

<40x306 sparse matrix of type '<class 'numpy.float64'>'
	with 465 stored elements in Compressed Sparse Row format>

In [62]:
s = cosine_similarity(x)

In [63]:
s.shape

(40, 40)

In [65]:
s /=s.sum(axis=1 , keepdims=True)

In [66]:
s[0].sum()

0.9999999999999999

In [68]:
U = np.ones_like(s)/len(s)

In [70]:
U[0].sum()

1.0

In [71]:
factor = 0.15
s= (1-factor)*s+factor*U

In [83]:
s[0].sum()

0.9999999999999998

In [87]:
eigenvals , eigenvec = np.linalg.eig(s.T)

In [88]:
eigenvals

array([1.        , 0.85      , 0.69820661, 0.67866975, 0.66693398,
       0.64977019, 0.16360507, 0.61147209, 0.59628992, 0.57348809,
       0.20367794, 0.55362853, 0.53795416, 0.2239143 , 0.52403415,
       0.23694364, 0.24219474, 0.50599101, 0.49544207, 0.2583628 ,
       0.26550538, 0.28131582, 0.2934101 , 0.29197691, 0.30625327,
       0.31822756, 0.32731376, 0.47578716, 0.46425109, 0.34198586,
       0.3511101 , 0.4518154 , 0.44868646, 0.42922839, 0.36684988,
       0.37497617, 0.3841921 , 0.3948407 , 0.413981  , 0.4074538 ])

In [89]:
eigenvec[: , 0].dot(s)

array([0.16442921, 0.22154641, 0.13981763, 0.15614761, 0.12775683,
       0.191188  , 0.12727125, 0.18125225, 0.17284846, 0.13560377,
       0.1824314 , 0.15315547, 0.13274475, 0.12974039, 0.14301994,
       0.15793095, 0.15834356, 0.15052921, 0.15637305, 0.15958111,
       0.16988563, 0.13068832, 0.16961636, 0.13323812, 0.13337835,
       0.14343576, 0.18042096, 0.12485333, 0.17240506, 0.1668514 ,
       0.12855429, 0.18548726, 0.12880394, 0.17203275, 0.16713454,
       0.1596071 , 0.13823211, 0.21433894, 0.15504606, 0.13920029])

In [90]:
eigenvec[: , 0]

array([0.16442921, 0.22154641, 0.13981763, 0.15614761, 0.12775683,
       0.191188  , 0.12727125, 0.18125225, 0.17284846, 0.13560377,
       0.1824314 , 0.15315547, 0.13274475, 0.12974039, 0.14301994,
       0.15793095, 0.15834356, 0.15052921, 0.15637305, 0.15958111,
       0.16988563, 0.13068832, 0.16961636, 0.13323812, 0.13337835,
       0.14343576, 0.18042096, 0.12485333, 0.17240506, 0.1668514 ,
       0.12855429, 0.18548726, 0.12880394, 0.17203275, 0.16713454,
       0.1596071 , 0.13823211, 0.21433894, 0.15504606, 0.13920029])

In [91]:
limt_dist = np.ones(len(s))/len(s)

In [92]:
thresh = 1e-8
delta = float('inf')
iters =0
while delta>thresh:
    iters+=1
    p= limt_dist.dot(s)
    delta= np.abs(p-limt_dist).sum()
    limt_dist=p
print(iters)

39


In [93]:
limt_dist

array([0.02628797, 0.03541953, 0.02235322, 0.02496396, 0.02042501,
       0.03056601, 0.02034738, 0.02897754, 0.02763399, 0.02167953,
       0.02916606, 0.02448559, 0.02122245, 0.02074213, 0.02286518,
       0.02524907, 0.02531503, 0.02406572, 0.025     , 0.02551289,
       0.02716031, 0.02089368, 0.02711726, 0.02130133, 0.02132374,
       0.02293166, 0.02884464, 0.01996081, 0.0275631 , 0.02667522,
       0.0205525 , 0.02965461, 0.02059241, 0.02750358, 0.02672048,
       0.02551704, 0.02209973, 0.03426724, 0.02478785, 0.02225452])

In [94]:
limt_dist.sum()

0.9999999999999984

In [97]:
np.abs(eigenvec[: , 0]/eigenvec[: , 0].sum()-limt_dist).sum()

1.8052880867286403e-08

In [98]:
scores = limt_dist
sort_idx = np.argsort(-scores)

In [99]:
def summary(text , factor=0.15):
    token = nltk.sent_tokenize(text)
    x = featurizer.fit_transform(token)
   
    s = cosine_similarity(x)
    s /=s.sum(axis=1 , keepdims=True)
    U = np.ones_like(s)/len(s)
    s= (1-factor)*s+factor*U
    eigenvals , eigenvec = np.linalg.eig(s.T)
    scores = eigenvec[: , 0]/eigenvec[: , 0].sum()
    sort_idx = np.argsort(-scores)


     
    for i in sort_idx[:5]:
        print(token[i])


In [101]:
doc = df[df.Type=='tech']['text'].sample(random_state=123)
summary(doc.iloc[0].split("\n" , 1)[1])

The Commodore 64 sold more than any other single computer system, even to this day.
In the late 1980s the firm was a great rival to Atari, which produced its own range of home computers and is now a brand of video games, formerly known as Infogrames.
The groundbreaking Commodore 64 computer elicits fond memories for those who owned one back in the 1980s.
The Commodore 64, launched in 1982, was one of the first affordable home PCs.

The once-famous Commodore computer brand could be resurrected after being bought by a US-based digital music distributor.


In [103]:
print(doc)

2197    Commodore finds new lease of life\n\nThe once-...
Name: text, dtype: object


libarary for summarizations

sumy , gensem