In [1]:
##https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing for word 2 vec
##

Word2Vec

In [1]:
from gensim.models import KeyedVectors as kv

In [2]:
word_vectors = kv.load_word2vec_format(r"D:\GoogleNews-vectors-negative300.bin\GoogleNews-vectors-negative300.bin" , binary=True)

In [10]:
def find_analogies(w1 , w2 , w3):
    r = word_vectors.most_similar(positive=[w1 , w3] , negative=[w2])
    print("%s - %s = %s - %s" %(w1 , w2 , r[0][0] , w3))

In [18]:
find_analogies("India" , "Hindi" , "China")

India - Hindi = Beijing - China


In [25]:
def nearest_neighbours(w):
    r= word_vectors.most_similar(positive=[w])
    print("neighbors of: %s" % w)
    for word , score in r:
        print("\t%s" % word)

In [28]:
nearest_neighbours('Japan')

neighbors of: Japan
	Japanese
	Japans
	South_Korea
	Tokyo
	Korea
	Japanâ_€_™
	Kurara_Chibana
	Shizuoka
	holder_Ryosuke_Irie
	Sachiko_Ito


GLOVE

In [7]:
##Glove
import numpy as np

In [8]:
def load_glove_vectors(glove_file):
    with open(glove_file, 'r', encoding="utf-8") as file:
        # unique words
        words = set()
        word_to_vec = {}
        # each line starts with a word then the values for the different features
        for line in file:
            line = line.strip().split()
            # take the word 
            curr_word = line[0]
            words.add(curr_word)
            # rest of the features for the word
            word_to_vec[curr_word] = np.array(line[1:], dtype=np.float64)
            
    return words, word_to_vec

In [9]:
words , word_to_vec =load_glove_vectors("D:\glove.6B\glove.6B.50d.txt")

In [75]:
arr= word_to_vec['king']-word_to_vec['man']+word_to_vec['woman']

In [ ]:
arr.reshape(-1 , 1)

In [11]:
m_cs=-999

In [36]:
arr

array([-0.29117  , -0.6723   ,  0.80732  , -0.111331 ,  1.25337  ,
       -0.58561  ,  0.067018 ,  0.00949  , -0.934332 , -0.44219  ,
       -0.152646 , -0.42698  , -1.425479 , -1.01507  ,  1.24     ,
       -0.20591  ,  0.38051  , -0.068301 , -1.05109  , -0.24928  ,
       -1.07146  ,  0.52615  ,  0.8079   , -0.03413  , -0.28052  ,
       -2.1848   , -0.63868  , -1.48188  ,  0.01216  , -0.125244 ,
        3.1046   ,  0.35726  , -0.77221  ,  0.08897  ,  0.48278  ,
        0.29474  , -0.117104 ,  0.166462 , -0.64275  ,  1.106816 ,
       -0.31483  ,  0.65287  ,  0.19897  ,  1.117    ,  1.0762   ,
       -0.15938  , -0.74861  , -0.27069  , -0.9382953, -0.66553  ])

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

In [64]:
words

{'weizenbaum',
 'abigail',
 'longirostris',
 'olla',
 'maquinaria',
 'slewing',
 'luv',
 'meson',
 'pacte',
 'silvassa',
 'chiclayo',
 'menemsha',
 'marsan',
 'transmogrified',
 'overhearing',
 '3.90',
 '50-54',
 'bigazzi',
 '24/7/365',
 'ajibade',
 'keteyian',
 'mahara',
 'crevasses',
 'student/teacher',
 'stereoisomer',
 'rigg',
 'robaina',
 'antuna',
 'katsonga',
 'maulavi',
 'ng/ml',
 'victrola',
 '4-iron',
 'tautological',
 'mayar',
 'bcms',
 'brnovic',
 '450-kilometer',
 '0.775',
 'tōkyū',
 'ructions',
 'purvi',
 'ence',
 'minus-5',
 'infusions',
 'digregorio',
 '81-73',
 'athlone',
 'yakou',
 'taegeuk',
 'pasa',
 'pawnbroker',
 'glücksburg',
 'mini-mart',
 'manganos',
 'partied',
 'kantner',
 'mokri',
 '21-stage',
 'palazzina',
 'lnbp',
 'dunstan',
 'ppc',
 'bektasevic',
 'basarwa',
 'khalkhali',
 'montefiore',
 '2000ad',
 'plescia',
 'rivlin',
 'verhulst',
 'two-wire',
 'akhal',
 'cicely',
 'baki',
 'cousin',
 'leaderships',
 'hartland',
 'nansen',
 'bunched',
 'chunming',
 'ab

In [65]:
def find_cosine_similarity(u, v):
    distance = 0.0
    
    # find the dot product between u and v 
    dot = np.dot(u,v)
    # find the L2 norm of u 
    norm_u = np.sqrt(np.sum(u**2))
    # Compute the L2 norm of v
    norm_v = np.sqrt(np.sum(v**2))
    # Compute the cosine similarity
    cosine_sim = dot/(norm_u*norm_v)
    
    return cosine_sim

In [66]:
cosine_similarity(word_to_vec['king'].reshape(-1 ,1) , word_to_vec['man'].reshape(-1 ,1)).flatten()

array([-1.,  1., -1., ...,  1., -1.,  1.])

In [79]:
m_cs=-999
f_w=""
for word in words:
    if word.lower() != 'king' and word.lower() != 'man' and word.lower() != 'woman' :
        w=word_to_vec[word]
        cs=find_cosine_similarity(w , arr)
        if cs>m_cs:
            m_cs=cs
            f_w=word
print(f_w)
print(m_cs)

queen
0.8609581258578943


In [68]:
word_to_vec['queen']

array([ 0.37854  ,  1.8233   , -1.2648   , -0.1043   ,  0.35829  ,
        0.60029  , -0.17538  ,  0.83767  , -0.056798 , -0.75795  ,
        0.22681  ,  0.98587  ,  0.60587  , -0.31419  ,  0.28877  ,
        0.56013  , -0.77456  ,  0.071421 , -0.5741   ,  0.21342  ,
        0.57674  ,  0.3868   , -0.12574  ,  0.28012  ,  0.28135  ,
       -1.8053   , -1.0421   , -0.19255  , -0.55375  , -0.054526 ,
        1.5574   ,  0.39296  , -0.2475   ,  0.34251  ,  0.45365  ,
        0.16237  ,  0.52464  , -0.070272 , -0.83744  , -1.0326   ,
        0.45946  ,  0.25302  , -0.17837  , -0.73398  , -0.20025  ,
        0.2347   , -0.56095  , -2.2839   ,  0.0092753, -0.60284  ])

In [108]:
def word_analogies(a , b , c): ##a-b=c+d
    m_cs=-999
    f_w=""
    arr=word_to_vec[a.lower()]-word_to_vec[b.lower()]+word_to_vec[c.lower()]
    for word in words:
        if word.lower() != a and word.lower() != b and word.lower() != c :
            w=word_to_vec[word]
            cs=find_cosine_similarity(w , arr)
            if cs>m_cs:
                m_cs=cs
                f_w=word
    return f_w , m_cs

In [114]:
word_analogies(a='usa' , b='russia' , c='india')

('mcgraw', 0.6376610090163514)

In [137]:
def most_similar(a):
    arr=word_to_vec[a.lower()]
    final_list=[] 
    for word in words:
        w=word_to_vec[word]
        cs=find_cosine_similarity(w , arr)
        final_list.append([word , cs])
    final_list.sort(reverse=True , key=lambda x: x[1])
    return final_list[1:11]

In [142]:
most_similar('japan')

[['japanese', 0.8822369967327616],
 ['china', 0.8428841684609186],
 ['korea', 0.8154973165622376],
 ['tokyo', 0.8078719738900642],
 ['taiwan', 0.7847011298330868],
 ['korean', 0.7758361697264494],
 ['asian', 0.7661137412814008],
 ['chinese', 0.7590301025471577],
 ['greece', 0.7550805928845414],
 ['beijing', 0.7429267927633294]]